apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
    name: instance
    namespace: openshift-logging
spec:
  inputs:
    - application:
        selector:
          matchLabels:
            logging: critical
      name: critical-apps
  outputs:
    - name: apps-tcp-syslog
      syslog:
        appName: ocp-console
        facility: user
        msgID: apps
        procID: apps
        rfc: RFC5424
        severity: informational
      type: syslog
      url: 'tcp://utility.lab.example.com:514'
    - name: apps-udp-syslog
      syslog:
        appName: ocp-console
        facility: user
        msgID: apps
        procID: apps
        rfc: RFC5424
        severity: informational
      type: syslog
      url: 'udp://utility.lab.example.com:514'
    - name: infra-tcp-syslog
      syslog:
        appName: ocp-console
        facility: user
        msgID: infra
        procID: infra
        rfc: RFC5424
        severity: informational
      type: syslog
      url: 'tcp://utility.lab.example.com:514'
    - name: infra-udp-syslog
      syslog:
        appName: ocp-console
        facility: user
        msgID: infra
        procID: infra
        rfc: RFC5424
        severity: informational
      type: syslog
      url: 'udp://utility.lab.example.com:514'
    - name: audit-tcp-syslog
      syslog:
        appName: ocp-console
        facility: user
        msgID: audit
        procID: audit
        rfc: RFC5424
        severity: informational
      type: syslog
      url: 'tcp://utility.lab.example.com:514'
    - name: audit-udp-syslog
      syslog:
        appName: ocp-console
        facility: user
        msgID: audit
        procID: audit
        rfc: RFC5424
        severity: informational
      type: syslog
      url: 'udp://utility.lab.example.com:514'
  pipelines:
    - inputRefs:
        - critical-apps
      name: apps-pipeline
      outputRefs:
        - apps-tcp-syslog
    - inputRefs:
        - infrastructure
      name: infra-pipeline
      outputRefs:
        - infra-tcp-syslog
    - inputRefs:
        - audit
      name: audit-pipeline
      outputRefs:
        - audit-tcp-syslog
